### ISSUE TITLE
Animation

### ISSUE THREAD

**Issue by Bloomca** [reactjs/react-modal#125]
Hi there!

I am wondering, what is the best approach to animate this modal?

The problem is – to create robust animation, which is easy to reuse across the whole application I have to create two wrappers to create actual animations and pass correct handlers to close modals.

So, what is the best way to deal with animations, is it possible with a single wrapper?
Maybe I just miss something obvious.

Thanks for any advice!

**Comment by megapctr** [comment]
Hi, you can try to start off by taking a look at this [example](https://reactcommunity.org/react-modal/bootstrap/)

Basically you add css for `.ReactModal__(Overlay/Content)--(after-open/before-close)` css classes

**Comment by megapctr** [comment]
Here's a snippet I came up with:
```scss
.ReactModalPortal > * {
    // When the modal is closed, overlay div has no css class
    // This selector should be overridden by the `&--after-open` class below
    opacity: 0;
}
.ReactModal__Overlay {
    transition: opacity 200ms ease-in-out;
    background: rgba(0, 0, 0, 0.15);
    &--after-open {
        opacity: 1;
    }
    &--before-close {
        opacity: 0;
    }
}
```

You should also provide a `closeTimeoutMS` prop to the `<Modal />` components, otherwise the closing animation will not work
