### ISSUE TITLE
Insert pseudo-elements in inline style

### ISSUE THREAD

**Issue by luis-alves** [reactjs/react-modal#547]
### Summary:
Been trying to draw a dialog box as the overlay. But don't know how to do it. It as to be inline because I want to assign the on-click pointer location to the top style element. SO the className is out of the question.

### Steps to reproduce:
https://codesandbox.io/s/xom5w2r1zp

### Expected behavior:
Should mold the form of the overlay to an dialog bubble, like the one in [https://css-tricks.com/examples/ShapesOfCSS/](https://css-tricks.com/examples/ShapesOfCSS/)

CSS code for the dialog bubble:

```css
#talkbubble {    
   width: 120px;  
   height: 80px;
   background: red;
   position: relative;
   -moz-border-radius:    10px;
   -webkit-border-radius: 10px;
   border-radius:         10px;
}
#talkbubble:before {
   content:"";
   position: absolute;
   right: 100%;
   top: 26px;
   width: 0;
   height: 0;
   border-top: 13px solid transparent;
   border-right: 26px solid red;
   border-bottom: 13px solid transparent;
}
```

### Example

https://codesandbox.io/s/xom5w2r1zp

### Additional notes:
And also is there support for `vendor-prefixed properties`? How can they be implemented, in inline styling of the React-Modal lib?
