### ISSUE TITLE
Opening modal causes body scroll top or bottom

### ISSUE THREAD

**Issue by prztrz** [reactjs/react-modal#585]
I have an issue that wehever I open the modal the body is immediatelly scrolled  to top or to bottom of the website. When the modal is closed the user is not in the place he/she opened the modal but either on the top or on the bottom of website.

I used following CSS to prevent parent element from scrolling (it allways causes the body scrolling top when modal is opened):

```css
.ReactModal__Body--open {
    overflow: hidden;
    position: fixed;
    width: 100%;
}
```

When I try to use just ```overflow:hidden``` as recommended in readme.md it does not work for me - the parent element is still scrollable.
When I try to use it without ```position: fixed``` as below: 

```css
.ReactModal__Body--open {
    overflow: hidden;
    width: 100%;
}
```
It always causes the body scroll bottom when modal is opened.

Skipping ```width: 100%``` causes the body content is shifted to the left if ```position: fixed``` is used as well.
